compsci-cluster-fitz-05
Tue Apr 22 06:52:45 PM EDT 2025
[I 2025-04-22 18:52:49.475 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-04-22 18:52:49.481 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-04-22 18:52:49.487 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-04-22 18:52:49.492 ServerApp] notebook | extension was successfully linked.
[I 2025-04-22 18:52:50.481 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-04-22 18:52:50.545 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-04-22 18:52:50.548 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-04-22 18:52:50.551 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-04-22 18:52:50.575 LabApp] JupyterLab extension loaded from /home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyterlab
[I 2025-04-22 18:52:50.575 LabApp] JupyterLab application directory is /home/users/ap794/final_project_distillLLM/venv/share/jupyter/lab
[I 2025-04-22 18:52:50.578 LabApp] Extension Manager is 'pypi'.
[I 2025-04-22 18:52:50.722 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-04-22 18:52:50.730 ServerApp] notebook | extension was successfully loaded.
[I 2025-04-22 18:52:50.731 ServerApp] Serving notebooks from local directory: /home/users/ap794/finalCS590-text2audiovideo/MM-Diffusion
[I 2025-04-22 18:52:50.731 ServerApp] Jupyter Server 2.15.0 is running at:
[I 2025-04-22 18:52:50.731 ServerApp] http://compsci-cluster-fitz-05:8888/tree?token=071d1132b54d397e730c2b43217fe8c3c34623a2ef8f2f62
[I 2025-04-22 18:52:50.731 ServerApp]     http://127.0.0.1:8888/tree?token=071d1132b54d397e730c2b43217fe8c3c34623a2ef8f2f62
[I 2025-04-22 18:52:50.731 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-04-22 18:52:50.738 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/users/ap794/.local/share/jupyter/runtime/jpserver-2399622-open.html
    Or copy and paste one of these URLs:
        http://compsci-cluster-fitz-05:8888/tree?token=071d1132b54d397e730c2b43217fe8c3c34623a2ef8f2f62
        http://127.0.0.1:8888/tree?token=071d1132b54d397e730c2b43217fe8c3c34623a2ef8f2f62
[I 2025-04-22 18:52:52.650 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-04-22 18:56:19.274 ServerApp] 302 GET / (@152.3.143.22) 1.21ms
[I 2025-04-22 18:56:19.285 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.38ms
[I 2025-04-22 18:56:21.304 ServerApp] 302 GET / (@152.3.143.22) 0.93ms
[I 2025-04-22 18:56:21.312 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.17ms
[I 2025-04-22 18:56:35.370 ServerApp] 302 GET / (@152.3.143.22) 0.90ms
[I 2025-04-22 18:56:35.392 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.13ms
[I 2025-04-22 18:56:35.726 ServerApp] Kernel started: 7f966573-7ee7-4a42-ad48-8fc92731178c
[I 2025-04-22 18:56:37.489 ServerApp] Connecting to kernel 7f966573-7ee7-4a42-ad48-8fc92731178c.
[I 2025-04-22 18:56:38.178 ServerApp] 302 GET / (@152.3.143.22) 0.82ms
[I 2025-04-22 18:56:38.178 ServerApp] 302 GET / (@152.3.143.22) 0.98ms
[I 2025-04-22 18:56:38.179 ServerApp] 302 GET / (@152.3.143.22) 0.42ms
[I 2025-04-22 18:56:38.365 ServerApp] 302 GET / (@152.3.143.22) 0.90ms
[I 2025-04-22 18:56:38.705 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.32ms
[I 2025-04-22 18:56:38.707 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.47ms
[I 2025-04-22 18:56:38.708 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.70ms
[I 2025-04-22 18:56:38.710 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.34ms
[W 2025-04-22 18:56:39.368 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:39.374 ServerApp] 403 GET /api/kernelspecs?1745362599183 (@152.3.143.22) 7.35ms referer=None
[W 2025-04-22 18:56:39.468 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:39.469 ServerApp] 403 GET /api/kernelspecs?1745362599368 (@152.3.143.22) 0.97ms referer=None
[W 2025-04-22 18:56:39.678 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:39.680 ServerApp] 403 GET /api/kernelspecs?1745362599472 (@152.3.143.22) 2.93ms referer=None
[W 2025-04-22 18:56:39.870 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:39.871 ServerApp] 403 GET /api/kernelspecs?1745362599763 (@152.3.143.22) 1.46ms referer=None
[W 2025-04-22 18:56:40.865 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.866 ServerApp] 403 GET /api/kernels?1745362599192 (@152.3.143.22) 1.93ms referer=None
[W 2025-04-22 18:56:40.867 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.867 ServerApp] 403 GET /api/kernels?1745362599372 (@152.3.143.22) 2.62ms referer=None
[W 2025-04-22 18:56:40.869 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.869 ServerApp] 403 GET /api/kernels?1745362599485 (@152.3.143.22) 1.70ms referer=None
[W 2025-04-22 18:56:40.870 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.870 ServerApp] 403 GET /api/kernels?1745362599972 (@152.3.143.22) 2.32ms referer=None
[W 2025-04-22 18:56:40.871 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.871 ServerApp] 403 GET /api/sessions?1745362599975 (@152.3.143.22) 2.94ms referer=None
[W 2025-04-22 18:56:40.871 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.872 ServerApp] 403 GET /api/kernels?1745362599866 (@152.3.143.22) 3.64ms referer=None
[W 2025-04-22 18:56:40.874 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.875 ServerApp] 403 GET /api/kernels?1745362599977 (@152.3.143.22) 2.42ms referer=None
[W 2025-04-22 18:56:40.875 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.876 ServerApp] 403 GET /api/sessions?1745362599984 (@152.3.143.22) 3.06ms referer=None
[W 2025-04-22 18:56:40.876 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.876 ServerApp] 403 GET /api/sessions?1745362599979 (@152.3.143.22) 3.67ms referer=None
[W 2025-04-22 18:56:40.877 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.877 ServerApp] 403 GET /api/kernels?1745362599981 (@152.3.143.22) 4.30ms referer=None
[W 2025-04-22 18:56:40.878 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.878 ServerApp] 403 GET /api/kernels?1745362599986 (@152.3.143.22) 4.92ms referer=None
[W 2025-04-22 18:56:40.879 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.879 ServerApp] 403 GET /api/sessions?1745362599988 (@152.3.143.22) 5.58ms referer=None
[W 2025-04-22 18:56:40.880 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.881 ServerApp] 403 GET /api/kernelspecs?1745362600773 (@152.3.143.22) 1.56ms referer=None
[W 2025-04-22 18:56:40.881 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.882 ServerApp] 403 GET /api/kernelspecs?1745362600787 (@152.3.143.22) 2.07ms referer=None
[W 2025-04-22 18:56:40.969 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.970 ServerApp] 403 GET /api/kernelspecs?1745362600788 (@152.3.143.22) 1.36ms referer=None
[W 2025-04-22 18:56:40.971 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:40.971 ServerApp] 403 GET /api/kernelspecs?1745362600789 (@152.3.143.22) 1.15ms referer=None
[I 2025-04-22 18:56:40.980 ServerApp] 302 GET / (@152.3.143.22) 0.36ms
[I 2025-04-22 18:56:40.981 ServerApp] 302 GET / (@152.3.143.22) 0.53ms
[I 2025-04-22 18:56:40.981 ServerApp] 302 GET / (@152.3.143.22) 0.63ms
[I 2025-04-22 18:56:41.273 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 0.79ms
[I 2025-04-22 18:56:41.683 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.62ms
[I 2025-04-22 18:56:41.684 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.98ms
[W 2025-04-22 18:56:41.802 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@152.3.143.22) 17.74ms referer=None
[I 2025-04-22 18:56:41.803 ServerApp] 302 GET / (@152.3.143.22) 17.91ms
[W 2025-04-22 18:56:41.870 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.872 ServerApp] 403 GET /api/kernelspecs?1745362601867 (@152.3.143.22) 2.13ms referer=None
[W 2025-04-22 18:56:41.875 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.876 ServerApp] 403 GET /api/kernelspecs?1745362601870 (@152.3.143.22) 2.02ms referer=None
[W 2025-04-22 18:56:41.878 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.879 ServerApp] 403 GET /api/kernelspecs?1745362601875 (@152.3.143.22) 1.90ms referer=None
[I 2025-04-22 18:56:41.966 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.06ms
[W 2025-04-22 18:56:41.969 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.971 ServerApp] 403 GET /api/kernels?1745362601867 (@152.3.143.22) 2.51ms referer=None
[W 2025-04-22 18:56:41.973 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.974 ServerApp] 403 GET /api/kernels?1745362601875 (@152.3.143.22) 2.28ms referer=None
[W 2025-04-22 18:56:41.977 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.983 ServerApp] 403 GET /api/kernels?1745362601872 (@152.3.143.22) 7.52ms referer=None
[W 2025-04-22 18:56:41.984 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.986 ServerApp] 403 GET /api/kernels?1745362601882 (@152.3.143.22) 9.91ms referer=None
[W 2025-04-22 18:56:41.986 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.987 ServerApp] 403 GET /api/sessions?1745362601883 (@152.3.143.22) 10.76ms referer=None
[W 2025-04-22 18:56:41.987 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.988 ServerApp] 403 GET /api/kernels?1745362601884 (@152.3.143.22) 11.44ms referer=None
[W 2025-04-22 18:56:41.992 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.993 ServerApp] 403 GET /api/sessions?1745362601886 (@152.3.143.22) 3.28ms referer=None
[W 2025-04-22 18:56:41.993 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.994 ServerApp] 403 GET /api/kernels?1745362601887 (@152.3.143.22) 3.86ms referer=None
[W 2025-04-22 18:56:41.995 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.995 ServerApp] 403 GET /api/sessions?1745362601888 (@152.3.143.22) 4.65ms referer=None
[W 2025-04-22 18:56:41.996 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.996 ServerApp] 403 GET /api/kernelspecs?1745362601895 (@152.3.143.22) 5.35ms referer=None
[W 2025-04-22 18:56:41.996 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.997 ServerApp] 403 GET /api/kernelspecs?1745362601894 (@152.3.143.22) 5.75ms referer=None
[W 2025-04-22 18:56:41.999 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:56:41.999 ServerApp] 403 GET /api/kernelspecs?1745362601896 (@152.3.143.22) 2.07ms referer=None
[W 2025-04-22 18:56:42.087 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@152.3.143.22) 2.51ms referer=None
[I 2025-04-22 18:57:39.881 ServerApp] Starting buffering for 7f966573-7ee7-4a42-ad48-8fc92731178c:e04c815c-8b45-4101-b73d-5a7b6cf528ff
[I 2025-04-22 18:57:42.068 ServerApp] 302 GET / (@152.3.143.22) 2.38ms
[I 2025-04-22 18:57:42.069 ServerApp] 302 GET / (@152.3.143.22) 2.25ms
[I 2025-04-22 18:57:42.070 ServerApp] 302 GET / (@152.3.143.22) 2.22ms
[I 2025-04-22 18:57:42.378 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.68ms
[I 2025-04-22 18:57:42.379 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 2.13ms
[I 2025-04-22 18:57:42.380 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.03ms
[W 2025-04-22 18:57:42.867 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:42.992 ServerApp] 403 GET /api/kernelspecs?1745362662863 (@152.3.143.22) 125.43ms referer=None
[W 2025-04-22 18:57:43.002 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.003 ServerApp] 403 GET /api/kernels?1745362662864 (@152.3.143.22) 9.40ms referer=None
[W 2025-04-22 18:57:43.004 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.005 ServerApp] 403 GET /api/kernels?1745362662867 (@152.3.143.22) 10.31ms referer=None
[W 2025-04-22 18:57:43.006 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.007 ServerApp] 403 GET /api/kernels?1745362662880 (@152.3.143.22) 11.39ms referer=None
[W 2025-04-22 18:57:43.008 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.009 ServerApp] 403 GET /api/sessions?1745362662881 (@152.3.143.22) 12.34ms referer=None
[W 2025-04-22 18:57:43.009 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.010 ServerApp] 403 GET /api/kernels?1745362662870 (@152.3.143.22) 12.80ms referer=None
[W 2025-04-22 18:57:43.010 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.011 ServerApp] 403 GET /api/kernels?1745362662883 (@152.3.143.22) 13.21ms referer=None
[W 2025-04-22 18:57:43.011 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.012 ServerApp] 403 GET /api/sessions?1745362662884 (@152.3.143.22) 13.68ms referer=None
[W 2025-04-22 18:57:43.013 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.013 ServerApp] 403 GET /api/kernels?1745362662885 (@152.3.143.22) 13.73ms referer=None
[W 2025-04-22 18:57:43.014 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.014 ServerApp] 403 GET /api/sessions?1745362662886 (@152.3.143.22) 14.09ms referer=None
[W 2025-04-22 18:57:43.015 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.016 ServerApp] 403 GET /api/kernelspecs?1745362662866 (@152.3.143.22) 14.68ms referer=None
[W 2025-04-22 18:57:43.016 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.017 ServerApp] 403 GET /api/kernelspecs?1745362662869 (@152.3.143.22) 15.34ms referer=None
[I 2025-04-22 18:57:43.088 ServerApp] 302 GET / (@152.3.143.22) 1.58ms
[I 2025-04-22 18:57:43.089 ServerApp] 302 GET / (@152.3.143.22) 1.51ms
[I 2025-04-22 18:57:43.092 ServerApp] 302 GET / (@152.3.143.22) 0.81ms
[I 2025-04-22 18:57:43.095 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.17ms
[I 2025-04-22 18:57:43.098 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.32ms
[I 2025-04-22 18:57:43.171 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.05ms
[W 2025-04-22 18:57:43.281 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.282 ServerApp] 403 GET /api/kernelspecs?1745362663262 (@152.3.143.22) 2.30ms referer=None
[W 2025-04-22 18:57:43.288 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.289 ServerApp] 403 GET /api/kernelspecs?1745362663170 (@152.3.143.22) 4.30ms referer=None
[W 2025-04-22 18:57:43.290 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.291 ServerApp] 403 GET /api/kernels?1745362663171 (@152.3.143.22) 5.66ms referer=None
[W 2025-04-22 18:57:43.299 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.300 ServerApp] 403 GET /api/kernels?1745362663173 (@152.3.143.22) 1.64ms referer=None
[W 2025-04-22 18:57:43.301 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.302 ServerApp] 403 GET /api/sessions?1745362663182 (@152.3.143.22) 1.59ms referer=None
[W 2025-04-22 18:57:43.386 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.387 ServerApp] 403 GET /api/kernelspecs?1745362663380 (@152.3.143.22) 2.20ms referer=None
[W 2025-04-22 18:57:43.389 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.391 ServerApp] 403 GET /api/kernels?1745362663272 (@152.3.143.22) 2.44ms referer=None
[W 2025-04-22 18:57:43.391 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.392 ServerApp] 403 GET /api/kernels?1745362663280 (@152.3.143.22) 3.63ms referer=None
[W 2025-04-22 18:57:43.465 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.466 ServerApp] 403 GET /api/sessions?1745362663283 (@152.3.143.22) 2.26ms referer=None
[W 2025-04-22 18:57:43.467 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.468 ServerApp] 403 GET /api/kernelspecs?1745362663298 (@152.3.143.22) 2.00ms referer=None
[W 2025-04-22 18:57:43.478 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.479 ServerApp] 403 GET /api/kernels?1745362663381 (@152.3.143.22) 2.08ms referer=None
[W 2025-04-22 18:57:43.481 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.482 ServerApp] 403 GET /api/sessions?1745362663389 (@152.3.143.22) 2.58ms referer=None
[W 2025-04-22 18:57:43.483 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.484 ServerApp] 403 GET /api/kernels?1745362663388 (@152.3.143.22) 3.76ms referer=None
[W 2025-04-22 18:57:43.486 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:57:43.487 ServerApp] 403 GET /api/kernelspecs?1745362663463 (@152.3.143.22) 2.05ms referer=None
[I 2025-04-22 18:58:20.086 ServerApp] 302 GET / (@152.3.143.22) 1.00ms
[I 2025-04-22 18:58:20.165 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.24ms
[I 2025-04-22 18:58:20.339 ServerApp] Kernel started: 587e8b08-4725-425d-8a95-9bb06b0cef44
[I 2025-04-22 18:58:21.725 ServerApp] Connecting to kernel 587e8b08-4725-425d-8a95-9bb06b0cef44.
[I 2025-04-22 18:58:22.009 ServerApp] 302 GET / (@152.3.143.22) 4.84ms
[I 2025-04-22 18:58:22.011 ServerApp] 302 GET / (@152.3.143.22) 5.68ms
[I 2025-04-22 18:58:22.011 ServerApp] 302 GET / (@152.3.143.22) 5.79ms
[I 2025-04-22 18:58:22.205 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 0.74ms
[I 2025-04-22 18:58:22.206 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 0.60ms
[I 2025-04-22 18:58:22.207 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 0.69ms
[W 2025-04-22 18:58:22.386 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.388 ServerApp] 403 GET /api/kernelspecs?1745362702383 (@152.3.143.22) 2.48ms referer=None
[W 2025-04-22 18:58:22.477 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.479 ServerApp] 403 GET /api/kernelspecs?1745362702473 (@152.3.143.22) 3.30ms referer=None
[W 2025-04-22 18:58:22.484 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.485 ServerApp] 403 GET /api/kernelspecs?1745362702480 (@152.3.143.22) 2.52ms referer=None
[W 2025-04-22 18:58:22.517 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.518 ServerApp] 403 GET /api/kernels?1745362702384 (@152.3.143.22) 1.76ms referer=None
[W 2025-04-22 18:58:22.520 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.521 ServerApp] 403 GET /api/kernels?1745362702397 (@152.3.143.22) 2.12ms referer=None
[W 2025-04-22 18:58:22.522 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.523 ServerApp] 403 GET /api/sessions?1745362702398 (@152.3.143.22) 3.53ms referer=None
[W 2025-04-22 18:58:22.581 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.582 ServerApp] 403 GET /api/kernels?1745362702474 (@152.3.143.22) 1.73ms referer=None
[W 2025-04-22 18:58:22.584 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.585 ServerApp] 403 GET /api/kernels?1745362702480 (@152.3.143.22) 1.59ms referer=None
[W 2025-04-22 18:58:22.598 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.600 ServerApp] 403 GET /api/kernelspecs?1745362702486 (@152.3.143.22) 2.12ms referer=None
[W 2025-04-22 18:58:22.603 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.604 ServerApp] 403 GET /api/kernels?1745362702487 (@152.3.143.22) 3.84ms referer=None
[W 2025-04-22 18:58:22.605 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.606 ServerApp] 403 GET /api/sessions?1745362702489 (@152.3.143.22) 5.15ms referer=None
[W 2025-04-22 18:58:22.607 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.608 ServerApp] 403 GET /api/kernels?1745362702490 (@152.3.143.22) 6.37ms referer=None
[W 2025-04-22 18:58:22.609 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.610 ServerApp] 403 GET /api/sessions?1745362702490 (@152.3.143.22) 7.56ms referer=None
[W 2025-04-22 18:58:22.611 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.612 ServerApp] 403 GET /api/kernelspecs?1745362702520 (@152.3.143.22) 9.15ms referer=None
[W 2025-04-22 18:58:22.614 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.615 ServerApp] 403 GET /api/kernelspecs?1745362702564 (@152.3.143.22) 1.86ms referer=None
[I 2025-04-22 18:58:22.615 ServerApp] 302 GET / (@152.3.143.22) 1.88ms
[I 2025-04-22 18:58:22.687 ServerApp] 302 GET / (@152.3.143.22) 0.47ms
[I 2025-04-22 18:58:22.688 ServerApp] 302 GET / (@152.3.143.22) 0.33ms
[I 2025-04-22 18:58:22.698 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 0.80ms
[I 2025-04-22 18:58:22.698 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 0.86ms
[W 2025-04-22 18:58:22.774 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.775 ServerApp] 403 GET /api/kernelspecs?1745362702728 (@152.3.143.22) 1.84ms referer=None
[W 2025-04-22 18:58:22.780 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.781 ServerApp] 403 GET /api/kernelspecs?1745362702777 (@152.3.143.22) 1.30ms referer=None
[W 2025-04-22 18:58:22.798 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.799 ServerApp] 403 GET /api/kernels?1745362702771 (@152.3.143.22) 0.78ms referer=None
[W 2025-04-22 18:58:22.799 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.800 ServerApp] 403 GET /api/kernels?1745362702773 (@152.3.143.22) 0.87ms referer=None
[W 2025-04-22 18:58:22.801 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.801 ServerApp] 403 GET /api/sessions?1745362702775 (@152.3.143.22) 0.68ms referer=None
[W 2025-04-22 18:58:22.802 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.802 ServerApp] 403 GET /api/kernels?1745362702778 (@152.3.143.22) 1.16ms referer=None
[W 2025-04-22 18:58:22.803 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.803 ServerApp] 403 GET /api/kernelspecs?1745362702783 (@152.3.143.22) 1.65ms referer=None
[W 2025-04-22 18:58:22.803 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.804 ServerApp] 403 GET /api/kernels?1745362702784 (@152.3.143.22) 2.03ms referer=None
[W 2025-04-22 18:58:22.804 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.804 ServerApp] 403 GET /api/sessions?1745362702786 (@152.3.143.22) 2.62ms referer=None
[W 2025-04-22 18:58:22.805 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.806 ServerApp] 403 GET /api/kernelspecs?1745362702795 (@152.3.143.22) 0.81ms referer=None
[I 2025-04-22 18:58:22.865 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.02ms
[W 2025-04-22 18:58:22.881 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.882 ServerApp] 403 GET /api/kernelspecs?1745362702877 (@152.3.143.22) 2.29ms referer=None
[W 2025-04-22 18:58:22.887 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.888 ServerApp] 403 GET /api/kernels?1745362702878 (@152.3.143.22) 2.15ms referer=None
[W 2025-04-22 18:58:22.890 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.891 ServerApp] 403 GET /api/kernels?1745362702879 (@152.3.143.22) 1.81ms referer=None
[W 2025-04-22 18:58:22.891 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.892 ServerApp] 403 GET /api/sessions?1745362702881 (@152.3.143.22) 2.57ms referer=None
[W 2025-04-22 18:58:22.894 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-04-22 18:58:22.895 ServerApp] 403 GET /api/kernelspecs?1745362702886 (@152.3.143.22) 1.64ms referer=None
[I 2025-04-22 18:58:29.896 ServerApp] Kernel interrupted: 587e8b08-4725-425d-8a95-9bb06b0cef44
[W 2025-04-22 18:58:32.199 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@152.3.143.22) 4.32ms referer=None
[I 2025-04-22 18:58:32.200 ServerApp] 302 GET / (@152.3.143.22) 4.19ms
[I 2025-04-22 18:58:32.210 JupyterNotebookApp] 302 GET /tree? (@152.3.143.22) 1.14ms
[W 2025-04-22 18:58:32.276 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@152.3.143.22) 2.32ms referer=None
[I 2025-04-22 19:00:02.764 ServerApp] Kernel interrupted: 587e8b08-4725-425d-8a95-9bb06b0cef44
[I 2025-04-22 19:00:03.642 ServerApp] Kernel interrupted: 587e8b08-4725-425d-8a95-9bb06b0cef44
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 8872709 ON compsci-cluster-fitz-05 CANCELLED AT 2025-04-22T19:05:03 ***
slurmstepd: error: *** STEP 8872709.2 ON compsci-cluster-fitz-05 CANCELLED AT 2025-04-22T19:05:03 ***
[C 2025-04-22 19:05:03.361 ServerApp] received signal 15, stopping
[I 2025-04-22 19:05:03.365 ServerApp] Shutting down 5 extensions
